version: '3'
services:
  todo: 
    build: .
    command: gunicorn --workers=3 -b 0.0.0.0:8000 app:app
    volumes:
      - /var/lib/jenkins/workspace/jenkins-docker-pipeline/todo.db:/app/todo.db
    ports:
      - "8000"
    

  nginx:
    image: nginx:1.23
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - todo
    ports:
      - "80:80"

